name: clgproject
description: A new Flutter application.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  timer_count_down: ^2.0.1
  audioplayers: ^0.19.0
  provider: ^5.0.0
  firebase_auth: ^3.0.1
  google_sign_in: ^5.0.5
  firebase_core: ^1.4.0
  font_awesome_flutter: ^9.1.0
  shared_preferences: ^2.0.6
  just_audio: ^0.9.4
  audio_service: ^0.17.1


dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true
  assets:
     - images/
     - assets/
  fonts:
     - family: Montserrat
       fonts:
         - asset: assets/Montserrat-Bold.ttf